---

#################################################################################
# Common Packages - i.e. chrome/vscode
#################################################################################

- hosts: all
  name: 'Install common packages'
  become: false
  gather_facts: false

  tasks:
    - name: Install vscode
      chocolatey.chocolatey.win_chocolatey:
        name:
          - vscode
        state: present
    # TODO: Add support for installing extensions
