---

#################################################################################
# Metasploit setup
#################################################################################

- hosts: all
  become: false
  vars:
    install_directory: '/home/vagrant/metasploit-framework'

  tasks:
    - name: Metasploit - Install RVM
      shell: |
        gpg --keyserver keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
        \curl -sSL https://get.rvm.io | bash -s stable
      args:
        creates: /home/vagrant/.rvm/scripts/rvm

    - name: Metasploit - Ensure RVM is available on path
      lineinfile:
        dest: '~/.zshrc'
        line: '[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"'

    - name: Metasploit - Clone
      git:
        repo: 'https://github.com/rapid7/metasploit-framework'
        dest: '{{ install_directory }}'
      register: clone

    - name: Metasploit - RVM Install
      when: clone.changed
      shell: |
        /bin/zsh --login -c 'rvm pkg install openssl && rvm install "$(cat .ruby-version)" --with-openssl-dir=$HOME/.rvm/usr'
      args:
        chdir: '{{ install_directory }}'

    - name: Metasploit - Bundle
      when: clone.changed
      shell: |
        /bin/zsh --login -c 'rvm use && bundle'
      args:
        chdir: '{{ install_directory }}'

    - name: Metasploit - Configure git fetch
      blockinfile:
        path: '{{ install_directory }}/.git/config'
        block: |
          [remote "upstream"]
            url = https://github.com/rapid7/metasploit-framework.git
            fetch = +refs/heads/*:refs/remotes/upstream/*
            fetch = +refs/pull/*/head:refs/remotes/upstream/pr/*
